# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := duktape duktape-hello duk loadlib-test test-module embed-js-module-test glue srduk duknode

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

duktape: 
	@echo "==== Building duktape ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f duktape.make

duktape-hello: duktape
	@echo "==== Building duktape-hello ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f duktape-hello.make

duk: duktape
	@echo "==== Building duk ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f duk.make

loadlib-test: duktape
	@echo "==== Building loadlib-test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f loadlib-test.make

test-module: duktape
	@echo "==== Building test-module ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test-module.make

embed-js-module-test: duktape
	@echo "==== Building embed-js-module-test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f embed-js-module-test.make

glue: 
	@echo "==== Building glue ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f glue.make

srduk: duktape
	@echo "==== Building srduk ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f srduk.make

duknode: duktape
	@echo "==== Building duknode ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f duknode.make

clean:
	@${MAKE} --no-print-directory -C . -f duktape.make clean
	@${MAKE} --no-print-directory -C . -f duktape-hello.make clean
	@${MAKE} --no-print-directory -C . -f duk.make clean
	@${MAKE} --no-print-directory -C . -f loadlib-test.make clean
	@${MAKE} --no-print-directory -C . -f test-module.make clean
	@${MAKE} --no-print-directory -C . -f embed-js-module-test.make clean
	@${MAKE} --no-print-directory -C . -f glue.make clean
	@${MAKE} --no-print-directory -C . -f srduk.make clean
	@${MAKE} --no-print-directory -C . -f duknode.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   duktape"
	@echo "   duktape-hello"
	@echo "   duk"
	@echo "   loadlib-test"
	@echo "   test-module"
	@echo "   embed-js-module-test"
	@echo "   glue"
	@echo "   srduk"
	@echo "   duknode"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
